#!/usr/bin/env node

/** 
 * This is the CLI application entry point, 
 * it calls main() function defined in main.js 
 * 
 * @author Frank Lacroix <lacroixdj@gmail.com.com>
*/
const main = require('./main.js');

main();